"""Recorder — turns the *actual executed actions* into a Capability artifact.

Decoupled from the LLM transcript by construction: the recorder never sees
model messages, only ``ExecutedAction`` records emitted by the executor for
actions that really ran and verified. Serialization steps:

* **Parameterization.** Concrete run values (the member number typed, the
  URL visited) are replaced by ``{param}`` templates / URL patterns. The
  artifact therefore contains no run-specific data — which is both what
  makes it reusable and what keeps PII out of it.
* **Checkpoint hardening.** The LLM's per-action ``success_text``
  expectations become recorded checkpoints — but only after a guard strips
  any that contain a run-specific input value (the model is instructed not
  to produce those; we don't rely on instructions alone).
* **Interstitial pruning.** Actions taken to dismiss a declared-known
  interstitial are excluded from the step list — they belong in
  ``recovery_rules`` (fire only when detected), not in the deterministic
  happy path.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from cua.browser import ElementInfo, build_locator_chain
from cua.discovery.spec import GoalSpec
from cua.safety.policy import PolicyGate
from cua.schema import (
    ActionType,
    BusinessOutcome,
    Capability,
    DiscoveryProvenance,
    ElementTarget,
    InputParam,
    Locator,
    LocatorStrategy,
    OutputField,
    RecoveryActionKind,
    RecoveryRule,
    StateProbe,
    Step,
    utc_now,
)


@dataclass
class ExecutedAction:
    """One action that actually ran during discovery (executor-emitted)."""

    tool: str  # navigate | click | fill | select | read
    args: dict
    element: ElementInfo | None
    url_before: str
    url_after: str
    success_text: str | None
    verified: bool
    was_interstitial_dismissal: bool = False
    read_value: str | None = None
    reason: str = ""


@dataclass
class Recording:
    actions: list[ExecutedAction] = field(default_factory=list)

    def add(self, action: ExecutedAction) -> None:
        self.actions.append(action)


_TOOL_TO_ACTION = {
    "navigate": ActionType.NAVIGATE,
    "click": ActionType.CLICK,
    "fill": ActionType.FILL,
    "select": ActionType.SELECT,
    "read": ActionType.READ,
}


def _slug(text: str, limit: int = 24) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s[:limit] or "step"


def parameterize_text(text: str, spec: GoalSpec) -> str:
    """Replace concrete input values with '{name}' templates (longest first)."""
    for p in sorted(spec.inputs, key=lambda p: -len(p.value)):
        if p.value:
            text = text.replace(p.value, "{" + p.name + "}")
    return text


def parameterize_url_pattern(url: str, spec: GoalSpec) -> str:
    """Escape a URL into a regex, generalizing input values to wildcards."""
    pattern = re.escape(url)
    for p in sorted(spec.inputs, key=lambda p: -len(p.value)):
        if p.value:
            pattern = pattern.replace(re.escape(p.value), "[^/?#]+")
    # Confirmation refs etc. also vary run-to-run; the recorder only knows
    # about declared inputs, so trailing opaque path segments generated by
    # the app (e.g. /confirm/SA-2026-0001) are generalized conservatively:
    pattern = re.sub(r"(/confirm/)[^/]+$", r"\1[^/]+", pattern)
    return pattern


def _strip_run_specific(text: str | None, spec: GoalSpec) -> str | None:
    """Drop checkpoint text that embeds run-specific values — guard rail."""
    if not text:
        return None
    for p in spec.inputs:
        if p.value and p.value in text:
            return None
    return text


def _row_scoped_control_selector(element: ElementInfo) -> str | None:
    """CSS fragment that identifies this control by tag + visible text/value,
    for use inside a row-scoped selector. Returns None for element kinds
    this doesn't know how to target this way (falls back to default
    behavior rather than emit a wrong selector)."""
    if element.tag in ("a", "button") and element.name:
        return f'{element.tag}:text-is("{element.name}")'
    if element.tag == "input" and element.name:
        return f'input[value="{element.name}"]'
    return None


def _reanchor_on_declared_input(
    target: ElementTarget, element: ElementInfo, spec: GoalSpec
) -> ElementTarget:
    """Fix two variants of the same underlying problem: a locator built from
    whatever's nearby in the DOM instead of the row's real identity.

    1. **Data cells** — ``build_locator_chain`` anchors a cell read on
       whatever text sits in the immediately preceding column, correct for
       label:value forms, wrong for a multi-column data table (every column
       is data; none of them is a durable label).
    2. **Controls repeated once per row** — a "View"/"Edit"-style link or
       button has the *same* accessible name in every row, so its role+name
       locator is inherently ambiguous across rows and silently resolves to
       whichever row the resolver's ambiguity/fallback handling happens to
       land on (verified: a positional fallback here clicked a *different*
       account's row than the one requested — wrong data, not a failure).

    Both are fixed the same way: if any cell in this row's captured text
    matches a declared input's concrete value exactly, that is the row's
    real stable identity — scope the locator to that specific row instead
    of trusting DOM adjacency or an ambiguous accessible name.

    The positional ``dom_path`` fallback is deliberately dropped once a
    re-anchor applies, in both cases. That fallback exists to survive minor
    markup drift on the *same* row (a drift canary) — it is not a
    legitimate substitute when the identity itself is genuinely absent (a
    value that doesn't belong to this member). A purely structural path
    still matches *some* row at that position regardless of whether the
    requested row exists, which would silently act on a different row
    instead of failing — worse than an error. Keeping only the
    identity-anchored locator means a nonexistent identity correctly fails
    resolution and goes through the normal three-bucket triage instead.
    """
    if not element.row_texts:
        return target
    if element.role == "cell" and (not element.col_index or element.label_source == "header"):
        # A header-sourced label identifies a column, not a row (the text
        # lives in a different row entirely) -- re-anchoring on a same-row
        # sibling's value doesn't apply here; build_locator_chain already
        # gives this case a purely positional locator, which is correct.
        return target
    for col, text in enumerate(element.row_texts, start=1):
        if element.role == "cell" and col == element.col_index:
            continue
        match = next((p for p in spec.inputs if p.value and p.value == text), None)
        if match is None:
            continue
        if element.role == "cell":
            target.locators = [
                Locator(
                    strategy=LocatorStrategy.CSS,
                    value=f'tr:has(td:text-is("{text}")) > td:nth-of-type({element.col_index})',
                    note=(
                        f"Anchored on the '{match.name}' column (this row's real "
                        "stable identity) rather than an adjacent value column. "
                        "No positional fallback -- see function docstring."
                    ),
                )
            ]
            target.description = f"the value cell in the row where {match.name} is \"{text}\""
        else:
            control = _row_scoped_control_selector(element)
            if control is None:
                continue
            target.locators = [
                Locator(
                    strategy=LocatorStrategy.CSS,
                    value=f'tr:has(td:text-is("{text}")) {control}',
                    note=(
                        f"Anchored on the '{match.name}' column so this control is "
                        "resolved within the correct row, not the first/nearest row "
                        "with a matching accessible name. No positional fallback -- "
                        "see function docstring."
                    ),
                )
            ]
            target.description = f"the \"{element.name}\" control in the row where {match.name} is \"{text}\""
        break
    return target


def _parameterize_target(target: ElementTarget, spec: GoalSpec) -> ElementTarget:
    """Apply the same '{param}' templating used for values/URLs to locator
    text — a literal that happens to equal a declared input's concrete
    value must not survive into the artifact, same as anywhere else."""
    target.description = parameterize_text(target.description, spec)
    for locator in target.locators:
        locator.value = parameterize_text(locator.value, spec)
        if locator.name:
            locator.name = parameterize_text(locator.name, spec)
    return target


def build_capability(
    spec: GoalSpec,
    recording: Recording,
    *,
    model_name: str,
    run_id: str,
    gate: PolicyGate,
) -> Capability:
    steps: list[Step] = []
    outputs: list[OutputField] = []

    # Step inclusion rule: an action is recorded if it truly executed AND
    # demonstrably advanced the flow. For fill/select/read, execution itself
    # verifies (read-back / extraction). For click/navigate we accept either
    # the model's expectation holding OR an observed URL transition — a
    # model can phrase its expectation slightly wrong ("Open New
    # Sub-Account" vs the page's "Open Sub-Account") while the action was
    # exactly right; dropping such a step would record a broken flow. A
    # click that neither met its expectation nor changed the URL is treated
    # as a no-op detour and excluded.
    def _advanced(a: ExecutedAction) -> bool:
        if a.tool in ("fill", "select", "read"):
            return a.verified
        return a.verified or a.url_after != a.url_before

    kept = [
        a
        for a in recording.actions
        if _advanced(a) and not a.was_interstitial_dismissal
    ]

    for i, action in enumerate(kept, start=1):
        action_type = _TOOL_TO_ACTION[action.tool]
        target: ElementTarget | None = (
            build_locator_chain(action.element) if action.element else None
        )
        if target is not None and action.element is not None:
            target = _reanchor_on_declared_input(target, action.element, spec)
            target = _parameterize_target(target, spec)
        label = action.element.name if action.element else action.url_after
        step_id = f"s{i:02d}_{action.tool}_{_slug(label)}"

        # A checkpoint text is recorded only if it (a) contains no
        # run-specific value and (b) actually held at discovery time — an
        # expectation the model got wrong must not become a permanent
        # assertion that fails every replay.
        checkpoint_text = (
            _strip_run_specific(action.success_text, spec)
            if action.verified
            else None
        )
        if action_type in (ActionType.NAVIGATE, ActionType.CLICK):
            checkpoint = StateProbe(
                url_pattern=parameterize_url_pattern(action.url_after, spec),
                text=checkpoint_text,
                description=(
                    f"after {action.tool}, the app shows "
                    f"{checkpoint_text or 'the expected page'} at the expected URL"
                ),
            )
        else:
            # fill/select/read: verification is intrinsic to the action
            # (read-back of the field value / successful text extraction);
            # the checkpoint asserts the control is still present & stable.
            checkpoint = StateProbe(
                target=target,
                description=f"the {action.tool} target is present and stable",
            )

        accessible_name = action.element.name if action.element else None
        risk = gate.classify(
            "click" if action_type == ActionType.CLICK else action_type.value,
            accessible_name,
        )

        step = Step(
            id=step_id,
            # Descriptions come from the model's stated reasoning, which may
            # mention concrete run values — parameterize them like any other
            # recorded text so no run data survives into the artifact.
            description=parameterize_text(
                action.reason or f"{action.tool} {label}", spec
            ),
            action=action_type,
            target=target,
            value_template=(
                parameterize_text(action.args["value"], spec)
                if action.tool in ("fill", "select")
                else None
            ),
            url_template=(
                parameterize_text(action.args["url"], spec)
                if action.tool == "navigate"
                else None
            ),
            output_name=action.args.get("output_name")
            if action.tool == "read"
            else None,
            risk=risk,
            checkpoint=checkpoint,
        )
        steps.append(step)

        if action.tool == "read":
            declared = next(
                (o for o in spec.outputs if o.name == action.args["output_name"]),
                None,
            )
            if declared:
                outputs.append(
                    OutputField(
                        name=declared.name,
                        kind=declared.kind,
                        description=declared.description,
                        source_step_id=step_id,
                        sensitivity=declared.sensitivity,
                    )
                )

    business_outcomes = [
        BusinessOutcome(
            code=o.code,
            description=o.description,
            detector=StateProbe(
                text=o.text,
                http_status=o.http_status,
                description=(
                    f"page shows: {o.text!r}"
                    + (f" (HTTP {o.http_status})" if o.http_status else "")
                ),
            ),
        )
        for o in spec.business_outcomes
    ]

    recovery_rules = [
        RecoveryRule(
            id=i.id,
            description=i.description,
            detector=StateProbe(
                text=i.text,
                http_status=i.http_status,
                description=(
                    f"page shows: {i.text!r}"
                    + (f" (HTTP {i.http_status})" if i.http_status else "")
                ),
            ),
            action_kind=RecoveryActionKind.CLICK,
            action_target=ElementTarget(
                description=f"the {i.dismiss_role} \"{i.dismiss_name}\" that dismisses the interstitial",
                locators=[
                    Locator(
                        strategy=LocatorStrategy.ROLE,
                        value=i.dismiss_role,
                        name=i.dismiss_name,
                        note="Interstitial dismiss control by role + accessible name.",
                    )
                ],
            ),
            max_applications=i.max_applications,
        )
        for i in spec.known_interstitials
    ]

    return Capability(
        capability_id=spec.capability_id,
        name=spec.name,
        description=(
            f"{spec.goal}\n\nReturns: "
            + (", ".join(f"{o.name} — {o.description}" for o in spec.outputs) or "no outputs")
            + ". Possible business outcomes: "
            + (", ".join(o.code for o in spec.business_outcomes) or "none declared")
            + "."
        ),
        provenance=DiscoveryProvenance(
            goal=spec.goal,
            model=model_name,
            run_id=run_id,
            discovered_at=utc_now(),
        ),
        entry_url_template=parameterize_text(spec.entry_url, spec),
        inputs=[
            InputParam(
                name=p.name,
                kind=p.kind,
                description=p.description,
                sensitivity=p.sensitivity,
                example=None if p.sensitivity.value != "public" else p.value,
            )
            for p in spec.inputs
        ],
        outputs=outputs,
        steps=steps,
        business_outcomes=business_outcomes,
        recovery_rules=recovery_rules,
    )
