"""Recorder — turns the *actual executed actions* into a Capability artifact.

Decoupled from the LLM transcript by construction: the recorder never sees
model messages, only ``ExecutedAction`` records emitted by the executor for
actions that really ran and verified. Serialization steps:

* **Parameterization.** Concrete run values (the member number typed, the
  URL visited) are replaced by ``{param}`` templates / URL patterns. The
  artifact therefore contains no run-specific data — which is both what
  makes it reusable and what keeps PII out of it.
* **Checkpoint hardening.** The LLM's per-action ``success_text``
  expectations become recorded checkpoints — but only after a guard strips
  any that contain a run-specific input value (the model is instructed not
  to produce those; we don't rely on instructions alone).
* **Interstitial pruning.** Actions taken to dismiss a declared-known
  interstitial are excluded from the step list — they belong in
  ``recovery_rules`` (fire only when detected), not in the deterministic
  happy path.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from cua.browser import ElementInfo, build_locator_chain
from cua.discovery.spec import GoalSpec
from cua.safety.policy import PolicyGate
from cua.schema import (
    ActionType,
    BusinessOutcome,
    Capability,
    DiscoveryProvenance,
    ElementTarget,
    InputParam,
    Locator,
    LocatorStrategy,
    OutputField,
    RecoveryActionKind,
    RecoveryRule,
    StateProbe,
    Step,
    utc_now,
)


@dataclass
class ExecutedAction:
    """One action that actually ran during discovery (executor-emitted)."""

    tool: str  # navigate | click | fill | select | read
    args: dict
    element: ElementInfo | None
    url_before: str
    url_after: str
    success_text: str | None
    verified: bool
    was_interstitial_dismissal: bool = False
    read_value: str | None = None
    reason: str = ""


@dataclass
class Recording:
    actions: list[ExecutedAction] = field(default_factory=list)

    def add(self, action: ExecutedAction) -> None:
        self.actions.append(action)


_TOOL_TO_ACTION = {
    "navigate": ActionType.NAVIGATE,
    "click": ActionType.CLICK,
    "fill": ActionType.FILL,
    "select": ActionType.SELECT,
    "read": ActionType.READ,
}


def _slug(text: str, limit: int = 24) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s[:limit] or "step"


def parameterize_text(text: str, spec: GoalSpec) -> str:
    """Replace concrete input values with '{name}' templates (longest first)."""
    for p in sorted(spec.inputs, key=lambda p: -len(p.value)):
        if p.value:
            text = text.replace(p.value, "{" + p.name + "}")
    return text


def parameterize_url_pattern(url: str, spec: GoalSpec) -> str:
    """Escape a URL into a regex, generalizing input values to wildcards."""
    pattern = re.escape(url)
    for p in sorted(spec.inputs, key=lambda p: -len(p.value)):
        if p.value:
            pattern = pattern.replace(re.escape(p.value), "[^/?#]+")
    # Confirmation refs etc. also vary run-to-run; the recorder only knows
    # about declared inputs, so trailing opaque path segments generated by
    # the app (e.g. /confirm/SA-2026-0001) are generalized conservatively:
    pattern = re.sub(r"(/confirm/)[^/]+$", r"\1[^/]+", pattern)
    return pattern


def _strip_run_specific(text: str | None, spec: GoalSpec) -> str | None:
    """Drop checkpoint text that embeds run-specific values — guard rail."""
    if not text:
        return None
    for p in spec.inputs:
        if p.value and p.value in text:
            return None
    return text


def build_capability(
    spec: GoalSpec,
    recording: Recording,
    *,
    model_name: str,
    run_id: str,
    gate: PolicyGate,
) -> Capability:
    steps: list[Step] = []
    outputs: list[OutputField] = []

    kept = [
        a
        for a in recording.actions
        if a.verified and not a.was_interstitial_dismissal
    ]

    for i, action in enumerate(kept, start=1):
        action_type = _TOOL_TO_ACTION[action.tool]
        target: ElementTarget | None = (
            build_locator_chain(action.element) if action.element else None
        )
        label = action.element.name if action.element else action.url_after
        step_id = f"s{i:02d}_{action.tool}_{_slug(label)}"

        checkpoint_text = _strip_run_specific(action.success_text, spec)
        if action_type in (ActionType.NAVIGATE, ActionType.CLICK):
            checkpoint = StateProbe(
                url_pattern=parameterize_url_pattern(action.url_after, spec),
                text=checkpoint_text,
                description=(
                    f"after {action.tool}, the app shows "
                    f"{checkpoint_text or 'the expected page'} at the expected URL"
                ),
            )
        else:
            # fill/select/read: verification is intrinsic to the action
            # (read-back of the field value / successful text extraction);
            # the checkpoint asserts the control is still present & stable.
            checkpoint = StateProbe(
                target=target,
                description=f"the {action.tool} target is present and stable",
            )

        accessible_name = action.element.name if action.element else None
        risk = gate.classify(
            "click" if action_type == ActionType.CLICK else action_type.value,
            accessible_name,
        )

        step = Step(
            id=step_id,
            description=action.reason or f"{action.tool} {label}",
            action=action_type,
            target=target,
            value_template=(
                parameterize_text(action.args["value"], spec)
                if action.tool in ("fill", "select")
                else None
            ),
            url_template=(
                parameterize_text(action.args["url"], spec)
                if action.tool == "navigate"
                else None
            ),
            output_name=action.args.get("output_name")
            if action.tool == "read"
            else None,
            risk=risk,
            checkpoint=checkpoint,
        )
        steps.append(step)

        if action.tool == "read":
            declared = next(
                (o for o in spec.outputs if o.name == action.args["output_name"]),
                None,
            )
            if declared:
                outputs.append(
                    OutputField(
                        name=declared.name,
                        kind=declared.kind,
                        description=declared.description,
                        source_step_id=step_id,
                        sensitivity=declared.sensitivity,
                    )
                )

    business_outcomes = [
        BusinessOutcome(
            code=o.code,
            description=o.description,
            detector=StateProbe(text=o.text, description=f"page shows: {o.text!r}"),
        )
        for o in spec.business_outcomes
    ]

    recovery_rules = [
        RecoveryRule(
            id=i.id,
            description=i.description,
            detector=StateProbe(text=i.text, description=f"page shows: {i.text!r}"),
            action_kind=RecoveryActionKind.CLICK,
            action_target=ElementTarget(
                description=f"the {i.dismiss_role} \"{i.dismiss_name}\" that dismisses the interstitial",
                locators=[
                    Locator(
                        strategy=LocatorStrategy.ROLE,
                        value=i.dismiss_role,
                        name=i.dismiss_name,
                        note="Interstitial dismiss control by role + accessible name.",
                    )
                ],
            ),
            max_applications=i.max_applications,
        )
        for i in spec.known_interstitials
    ]

    return Capability(
        capability_id=spec.capability_id,
        name=spec.name,
        description=(
            f"{spec.goal}\n\nReturns: "
            + (", ".join(f"{o.name} — {o.description}" for o in spec.outputs) or "no outputs")
            + ". Possible business outcomes: "
            + (", ".join(o.code for o in spec.business_outcomes) or "none declared")
            + "."
        ),
        provenance=DiscoveryProvenance(
            goal=spec.goal,
            model=model_name,
            run_id=run_id,
            discovered_at=utc_now(),
        ),
        entry_url_template=parameterize_text(spec.entry_url, spec),
        inputs=[
            InputParam(
                name=p.name,
                kind=p.kind,
                description=p.description,
                sensitivity=p.sensitivity,
                example=None if p.sensitivity.value != "public" else p.value,
            )
            for p in spec.inputs
        ],
        outputs=outputs,
        steps=steps,
        business_outcomes=business_outcomes,
        recovery_rules=recovery_rules,
    )
